import abc
import re
from typing import List, Dict, Optional

class BaseReplyProvider(abc.ABC):
    @abc.abstractmethod
    def generate_reply(self, customer_message: str, intent: str, formatted_evidence: str, context: Optional[str] = None) -> Dict:
        """
        Generates a grounded customer support reply.
        Returns a dict with: reply, grounding_summary, evidence_used, confidence, warnings.
        """
        pass

class LLMReplyProvider(BaseReplyProvider):
    def __init__(self, mock_mode: bool = False):
        self.mock_mode = mock_mode
        if not self.mock_mode:
            import os
            from openai import OpenAI
            api_key = (os.getenv("OPENROUTER_API_KEY") or os.getenv("OPENAI_API_KEY") or "").strip().strip('"\'')
            base_url = os.getenv("OPENAI_BASE_URL", "https://openrouter.ai/api/v1")
            self.client = OpenAI(
                api_key=api_key,
                base_url=base_url
            )
            self.model_name = os.getenv("LLM_MODEL", "openai/gpt-4o-mini")

    def generate_reply(self, customer_message: str, intent: str, formatted_evidence: str, context: Optional[str] = None) -> Dict:
        if self.mock_mode:
            return MockReplyProvider().generate_reply(customer_message, intent, formatted_evidence, context)

        import os
        import time
        import json
        import openai
        
        prompt = f"""
You are an AI customer support agent for AmazonHelp.
Your task is to draft a reply to the customer's message based STRICTLY on the historical evidence provided.

Customer Message:
{customer_message}

Predicted Intent:
{intent}

Historical Evidence:
{formatted_evidence}

Rules:
- Prioritize evidence relevant to the customer's intent.
- Avoid inventing policies, refunds, timelines, guarantees, compensation, or account actions.
- Never claim that an action was performed.
- Never expose internal reasoning or private system information.
- Do not mention that this answer was generated by an AI.
- Remain concise and natural.
- If the evidence does not provide enough information to safely answer, do NOT fabricate an answer. Return a safe fallback indicating human support is needed and set a warning.

You must respond in strict JSON matching the following schema:
{{
  "reply": "The text of your response to the customer",
  "grounding_summary": "A short sentence explaining what evidence justifies the reply",
  "evidence_used": [123.0, 456.0],
  "confidence": 0.9,
  "warnings": ["warning 1"]
}}
"""
        max_retries = int(os.getenv("LLM_MAX_RETRIES", "5"))
        base_delay = float(os.getenv("LLM_REQUEST_DELAY_SECONDS", "3.0"))
        
        time.sleep(base_delay)
        
        for attempt in range(max_retries):
            try:
                response = self.client.chat.completions.create(
                    model=self.model_name,
                    messages=[
                        {"role": "system", "content": "You are an AI customer support agent for AmazonHelp.\nYou must respond in strict JSON."},
                        {"role": "user", "content": prompt}
                    ],
                    response_format={"type": "json_object"},
                    temperature=0.0
                )
                
                raw_json = response.choices[0].message.content
                try:
                    parsed = json.loads(raw_json)
                    return {
                        "reply": str(parsed.get("reply", "I apologize, but I need a human agent to look into this specific issue. Please wait while I transfer you.")),
                        "grounding_summary": str(parsed.get("grounding_summary", "No summary provided.")),
                        "evidence_used": parsed.get("evidence_used", []),
                        "confidence": float(parsed.get("confidence", 0.0)),
                        "warnings": parsed.get("warnings", [])
                    }
                except (json.JSONDecodeError, ValueError, TypeError) as e:
                    return {
                        "reply": "I apologize, but I need a human agent to look into this specific issue. Please wait while I transfer you.",
                        "grounding_summary": "Failed to parse JSON.",
                        "evidence_used": [],
                        "confidence": 0.0,
                        "warnings": [f"Failed to parse LLM response: {str(e)}"]
                    }
                    
            except (openai.RateLimitError, openai.APIConnectionError, openai.APIError) as e:
                if attempt == max_retries - 1:
                    raise
                sleep_time = (2 ** attempt) * base_delay
                time.sleep(sleep_time)
                
        return {
            "reply": "I apologize, but I need a human agent to look into this specific issue. Please wait while I transfer you.",
            "grounding_summary": "Retries exhausted.",
            "evidence_used": [],
            "confidence": 0.0,
            "warnings": ["API retries exhausted"]
        }

class MockReplyProvider(BaseReplyProvider):
    def generate_reply(self, customer_message: str, intent: str, formatted_evidence: str, context: Optional[str] = None) -> Dict:
        if not formatted_evidence.strip():
            return {
                "reply": "I apologize, but I need a human agent to look into this specific issue. Please wait while I transfer you.",
                "grounding_summary": "No evidence provided.",
                "evidence_used": [],
                "confidence": 0.0,
                "warnings": ["Insufficient evidence: triggered safe fallback."]
            }
            
        # Parse root_ids from formatted evidence to mock evidence_used
        root_ids = re.findall(r"Root ID: (\d+\.?\d*)", formatted_evidence)
        evidence_used = [float(r) for r in root_ids]
        
        return {
            "reply": "[MOCK] We understand your concern. Please reach out to our team via DM with your details so we can assist further.",
            "grounding_summary": "Mock summary based on evidence.",
            "evidence_used": evidence_used,
            "confidence": 0.95,
            "warnings": []
        }

class ReplyGenerator:
    def __init__(self, provider: BaseReplyProvider):
        self.provider = provider
        
    def _format_evidence(self, retrieved_examples: List[Dict]) -> str:
        if not retrieved_examples:
            return ""
            
        lines = []
        for i, ex in enumerate(retrieved_examples, 1):
            lines.append(f"--- Example {i} ---")
            lines.append(f"Root ID: {ex.get('root_id', 'Unknown')}")
            lines.append(f"Intent: {ex.get('intent', 'Unknown')}")
            lines.append(f"Similarity Score: {ex.get('similarity_score', 0.0):.3f}")
            lines.append(f"Historical Customer Message:\n{ex.get('customer_message', '')}")
            lines.append(f"Historical AmazonHelp Response:\n{ex.get('historical_response', '')}")
            lines.append("")
            
        return "\n".join(lines).strip()
        
    def generate(self, customer_message: str, intent: str, retrieved_examples: List[Dict], context: Optional[str] = None) -> Dict:
        formatted_evidence = self._format_evidence(retrieved_examples)
        return self.provider.generate_reply(customer_message, intent, formatted_evidence, context)
