with open('README.md', 'a', encoding='utf-8') as f:
    f.write("\n## Phase 3: Data Foundation & Baselines\n")
    f.write("\nIn this phase, we constructed a robust, leakage-free data evaluation framework.\n")
    f.write("\n### Methodology\n")
    f.write("- **Split Strategy**: The data is split at the `root_id` (conversation thread) level to ensure no tweets from the same thread cross the Train/Validation/Test boundaries. The target split is 80% Train, 10% Validation, 10% Internal Test.\n")
    f.write("- **Leakage Prevention**: To prevent label leakage, contextual models strictly use messages that occurred *before* the target customer message. Future messages and the brand's response to the target message are aggressively filtered out.\n")
    f.write("- **Representations**: We implemented a context ablation study comparing `MESSAGE_ONLY` (just the target tweet) against `CONVERSATION_CONTEXT` (the target tweet + up to 3 preceding messages).\n")
    f.write("- **Baselines**: A Majority Class baseline and two TF-IDF + Logistic Regression baselines were implemented using weak labels generated via taxonomy keywords.\n")
    f.write("\n### Reproducing Phase 3\n")
    f.write("```bash\n")
    f.write("# 1. Generate splits and weak labels\n")
    f.write("python scripts/create_splits.py --input data/twcs.csv\n\n")
    f.write("# 2. Train baseline models\n")
    f.write("python scripts/train_baselines.py\n\n")
    f.write("# 3. Evaluate models and run context ablation study\n")
    f.write("python scripts/evaluate_baselines.py\n\n")
    f.write("# 4. Run data integrity and leakage tests\n")
    f.write("python tests/test_data_leakage.py\n")
    f.write("```\n")
    f.write("\n### Phase 3 Reports\n")
    f.write("- `reports/context_ablation.md`: Results comparing Message-Only vs Context-Aware performance.\n")
    f.write("- `reports/error_analysis.json`: Representative baseline failures.\n")
